[project]
name = "anychat"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ai-gradio[huggingface]==0.2.54",
]

[tool.uv.sources]


[tool.ruff]
line-length = 119

[tool.ruff.lint]
select = [
    "E",
    "F",
    #"I",
    "N",
    "S",
    "T",
    "UP",
    "W",
]
ignore = ["T201"]
unfixable = [
    "F401", # unused-import
]

[tool.ruff.format]
docstring-code-format = true
